# Generated by Django 3.1 on 2020-09-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('userid', models.CharField(max_length=50)),
                ('remark', models.TextField(max_length=1000)),
                ('status', models.BooleanField()),
                ('odate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='signup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50)),
                ('address', models.TextField(max_length=500)),
                ('mob', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=50)),
                ('userpic', models.ImageField(default='', upload_to='static/profile/')),
                ('passwd', models.CharField(max_length=50)),
            ],
        ),
    ]
